# General settings
format = """$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$python\
$golang\
$cmd_duration\
$line_break\
$character"""

# Set palette based on Tokyo Night Storm theme
palette = "tokyonight"

[palettes.tokyonight]
blue = "#7aa2f7"
green = "#9ece6a"
purple = "#bb9af7"
red = "#f7768e"
yellow = "#e0af68"
gray = "#565f89"
fg = "#c0caf5"
bg = "#24283b"

# Directory config
[directory]
style = "fg:blue"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Git branch
[git_branch]
symbol = " "
style = "fg:purple"
format = '[ $symbol$branch ]($style)'

# Git status
[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
conflicted = "≠"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
style = "fg:red"
format = '([\[$all_status$ahead_behind\] ]($style))'

# Language versions
[nodejs]
symbol = " "
style = "bg:bg fg:green"
format = '[[ $symbol ($version) ](fg:green bg:bg)]($style)'

[rust]
symbol = " "
style = "bg:bg fg:yellow"
format = '[[ $symbol ($version) ](fg:yellow bg:bg)]($style)'

[python]
symbol = " "
style = "bg:bg fg:yellow"
format = '[[ $symbol ($version) ](fg:yellow bg:bg)]($style)'

[golang]
symbol = " "
style = "bg:bg fg:blue"
format = '[[ $symbol ($version) ](fg:blue bg:bg)]($style)'

# Command duration
[cmd_duration]
style = "fg:gray"
format = '[ 󱎫 $duration]($style)'
min_time = 500

# Prompt character
[character]
success_symbol = "[](fg:blue)[➜](fg:green)"
error_symbol = "[](fg:blue)[✗](fg:red)"